"""Data models and schemas for FinOps Wizard.

Defines Pydantic models for reporting, discovery output, inventory status,
and analysis details with structural consistency.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ProviderType(str, Enum):
    """Supported cloud provider types."""
    AWS = "aws"
    GCP = "gcp"
    AZURE = "azure"


class WorkloadType(str, Enum):
    """Supported workload types for auto-detection."""
    K8S = "k8s"
    SERVERLESS = "serverless"
    VMS = "vms"


class DiscoveryReport(BaseModel):
    """Phase 1: Discovery baseline assessment report.
    
    Contains initial billing parameters, anomaly counts, tag statistics,
    and the list of workloads auto-detected in the cloud account.
    """
    timestamp: datetime = Field(default_factory=datetime.now)
    provider: ProviderType
    mode: str  # "cloud" or "workloads"
    monthly_burn_rate: float
    detected_anomalies: int
    tag_coverage_pct: float
    detected_workloads: List[WorkloadType]
    raw_billing_metrics: Dict[str, Any] = Field(default_factory=dict)
    dry_run_commands: List[str] = Field(default_factory=list)


class InventoryItem(BaseModel):
    """Individual cloud resource utilization profile."""
    resource_id: str
    resource_name: str
    resource_type: str  # e.g., "virtual_machine", "kubernetes_pod", "lambda_function", "ebs_volume"
    workload_type: WorkloadType
    monthly_cost: float
    utilization_metrics: Dict[str, Any] = Field(default_factory=dict)
    tags: Dict[str, str] = Field(default_factory=dict)
    is_waste: bool = False
    waste_reason: Optional[str] = None


class InventoryReport(BaseModel):
    """Phase 2: Inventory utilization mapping report."""
    timestamp: datetime = Field(default_factory=datetime.now)
    provider: ProviderType
    mode: str
    total_resources: int
    waste_resources: int
    potential_savings: float
    items: List[InventoryItem] = Field(default_factory=list)
    dry_run_commands: List[str] = Field(default_factory=list)


class OptimizationRecommendation(BaseModel):
    """Individual recommendations generated by the LLM analysis."""
    title: str
    description: str
    impact: str  # "low", "medium", "high"
    potential_savings: float
    resource_id: Optional[str] = None
    terraform_file: Optional[str] = None
    patch: Optional[str] = None  # Unified diff/patch for IaC files


class AnalysisReport(BaseModel):
    """Phase 3: Analysis report summarizing optimization recommendations."""
    timestamp: datetime = Field(default_factory=datetime.now)
    provider: ProviderType
    mode: str
    summary_markdown: str
    recommendations: List[OptimizationRecommendation] = Field(default_factory=list)
